Added screenshorts and hints
stalj/data-notations pull request #5
Opened 2024-10-02 21:44 UTC by SvitlanaDidkivska

In several places, it seemed that for novice users text instructions only might be not enough for clear understanding.

IMO several screenshots would be a good addition to the instructions.

2024-10-03 20:09 UTC, stalj commented on 02-DocumentVersionTracking/DocumentVersionTracking.md
> +    ![](screenshots/new_repository_creation_on_github.jpg)
1. It has to be public, not private, repository to control students' progress. So please modify the screen and mark the public
2. I also suggest doing some red circle/oval around the 'Repository name' field, as you did on the other screenshots

2024-10-03 20:09 UTC, stalj commented on 02-DocumentVersionTracking/DocumentVersionTracking.md
> +        ![](screenshots/place_where_you_can_copy_your_project_HTTPS.jpg)
IMO please add some red oval around:
1. The green 'Code' button
2. The http address and copy button on the right

2024-10-03 20:09 UTC, stalj commented on 02-DocumentVersionTracking/DocumentVersionTracking.md
> +![](screenshots/Display_the_content_of_created_repository_in_VSCode.jpg)
As far as I remember, the Welcome screen is swithed off in the computer labs. So you could red mark the Documents icon (first in the left panel) and create som hint on how to do with opening a folder

BTW, I have prepared a dedicated copy of VSCode with some necessary extensions for this course. In the computer labs, on the Windows desktop, you should find a VSC folder and in it, two VSCodes: one for my course in Java and one for this Data Notations course.

2024-10-04 14:22 UTC, stalj requested changes
I added some comments to your changes, especially to modify scrennshots.

2024-10-05 10:10 UTC, SvitlanaDidkivska commented on 02-DocumentVersionTracking/DocumentVersionTracking.md
> +    ![](screenshots/new_repository_creation_on_github.jpg)
Changes submitted.

2024-10-05 10:10 UTC, SvitlanaDidkivska commented on 02-DocumentVersionTracking/DocumentVersionTracking.md
> +        ![](screenshots/place_where_you_can_copy_your_project_HTTPS.jpg)
Changes submitted.

2024-10-05 10:11 UTC, SvitlanaDidkivska commented on 02-DocumentVersionTracking/DocumentVersionTracking.md
> +![](screenshots/Display_the_content_of_created_repository_in_VSCode.jpg)
Changes submitted.

2024-10-05 16:56 UTC, stalj approved these changes

2024-10-05 16:56 UTC, merged